### ISSUE TITLE
Feedback on new GUI

### ISSUE THREAD

**Issue by Krougal** [Astavie/ThermalLogistics#51]
The new GUI, TLDR it's awful.

![2021-01-06_17 00 10](https://user-images.githubusercontent.com/7410326/103824194-6c991480-5041-11eb-9fea-c8f5cd6aab21.png)

Everything is off. This happens to be auto scale, but I cycled through all the sizes and it doesn't make a difference. 

The crafting interface is extremely clunky. It's uncomfortable to use starting with having to close it to select a new recipe all the way through requesting being unavailable as it cycles through ore dictionary entries for inputs. It's been quite some time since I played with 1.12 but this seems to be complete trash compared to how it used to work (which might have been basic but functional).

![2021-01-06_17 00 57](https://user-images.githubusercontent.com/7410326/103824449-ee893d80-5041-11eb-9470-a72a7cb6a100.png)

Then there is the crafter. I can't seem to select the quantity with the JEI ghost items. Example shown is for the TE sawmill, 1 wood to 6 planks. Being as I only have oak planks on me, I was only able to properly set it for that.

Also don't care for the change from redstone to activate/deactive buttons. It might be handy as an addition but it is all very inconsistent with TD now.

**Comment by Astavie** [comment]
It's funny how you called this "feedback on new gui" as if you're dissatisfied with the design but what you're mostly describing is are bugs.

No, the terminal isn't supposed to look broken. No the crafting tab isn't supposed to function any different.

The jei ghost items have always functioned that way, but you're right that they're a bit clunky.

Also, what's up with that screenshot of the crafter? Is that how it always looks to you? [Edit: looks like the crafter gui is also a resource pack issue]

Also, in regards to the terminal being off: it looks like you're using a custom texture for the gui, perhaps this texture is outdated and meant for 0.2

So the only intentional design decision here are the on/off buttons. This has been done so you can easily turn off one recipe at a time and also turn off all linked crafters at once. It's inconsistent with the rest of TD, yes, but redstone control doesn't give you this fine of control. 

I'll try to fix the bugs with the crafting tab and the jei ghost items.

**Comment by Krougal** [comment]
Well it was a tossup between bugs and design I guess.
I've got resource packs but I don't think any of them should have textures for TL unless you are using certain default textures.
No the crafter never looked like this. Here's an old example: https://forum.feed-the-beast.com/attachments/2019-11-15_19-28-19-png.37468/

I don't have that particular game installation anymore since that computer died and backups were incomplete/partially corrupted, but it's highly likely the same resource packs I was using then. 

Compared screenshot of terminal and you're right, it is the same (other than being misaligned), although I remember the crafting grid being easier to work with.

**Comment by Astavie** [comment]
I can clearly see in the screenshots that the terminal gui has more pixels than usual, which signals that you're using a resource pack that indeed has TL textures. Try removing them and see if it fixes it?

Edit: for clarification, I changed the terminal gui texture and crafting gui texture between 0.2 and 0.3 and your screenshot looks like 0.3 code using a texture meant for 0.2

**Comment by Astavie** [comment]
I'm also intrigued which resource pack included textures for TL 🤔

**Comment by Krougal** [comment]
I pulled them all out and put them back 1 by 1 and it would appear that Faithful32 is the culprit. Specificaly Faithful32 with mod support.
https://www.curseforge.com/minecraft/texture-packs/faithful32-modded
Edits: Sorry, got confused since I have 4 different Faithful variants installed.

**Comment by Krougal** [comment]
Ahhh look at that, there you are:
![image](https://user-images.githubusercontent.com/7410326/103924719-6f007a80-50e4-11eb-843d-1c555f8a2a7d.png)

I made an issue on their git.

**Comment by Astavie** [comment]
0.3-42 should fix most of these ^^

**Comment by AbieTheFishman** [comment]
Thanks all - I was having same issue: Faithful32
