### ISSUE TITLE
Crash with AE2

### ISSUE THREAD

**Issue by monokin1114** [Astavie/ThermalLogistics#8]
I am having a crash on a server I run. But its only on the server not on the client.
I can load the same mods and a world on a single player instance. But on a instance on my server I get this crash.
I have attached the PasteBin.
https://pastebin.com/ZzcuBUj9

**Comment by Astavie** [comment]
When does this crash happen?

**Comment by monokin1114** [comment]
Happens on server load

**Comment by Astavie** [comment]
You might have to report this to AE2 (since its AE2 that's crashing here).

**Comment by Astavie** [comment]
Are you using a custom mod that runs `
FMLInterModComms.sendMessage( "appliedenergistics2", "whitelist-spatial", "astavie.thermallogistics.gui.client.GuiTerminal" );` or using `Spatial.whitelistEntity("astavie.thermallogistics.gui.client.GuiTerminal");` in CraftTweaker? Because I think you want it to be `astavie.thermallogistics.tile.TileTerminalItem`

**Comment by monokin1114** [comment]
Let me test. I think I have figured it out by you saying that

**Comment by monokin1114** [comment]
So it is a incompatibility with SpactialCompat. Will report to that mod

**Comment by Astavie** [comment]
Seems MrDj200/SpatialComapt#3 is the same issue
